[package]
name = "pinball3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
bevy = { version = "0.15", default-features = false, features = [
    "bevy_asset",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "png",
    "x11",
    "tonemapping_luts",
    "multi_threaded",
] }
bevy_rapier3d = "0.28"

[profile.release]
opt-level = 'z'
